export default {
  username: 'Hey, Rahul',
  details: 'Details',
  home: 'Home',
  more: 'More',
  favourite: 'Favourite',
  category: 'Category',
  cart: 'Cart',
  change_language: 'Change Language',
  search: 'Search Products or store',
  delivery: 'DELIVERY TO',
  address: 'Green Way 3000, Sylhet',
  within: 'WITHIN',
  hour: '1 Hour',
};
