export default {
  username: 'Hey, Rahul',
  details: 'Details',
  home: 'Home',
  more: 'More',
  favourite: 'Favourite',
  category: 'Categories',
  cart: 'Cart',
  change_language: 'Change Language',
  search: 'Search Products or store',
  delivery: 'DELIVERY TO',
  address: 'Green Way 3000, Sylhet',
  within: 'WITHIN',
  hour: '1 Hour',
  recommended: 'Recommended',
  discount: '50% OFF',
  get: 'GET',
  order: 'On first 03 order',
  off: 'OFF',
  shopping: 'Shopping Cart',
  subTotal: 'Subtotal',
  deliveryPrice: 'Delivery',
  total: 'Total',
  addToCart: 'Add To Cart',
  buyNow: 'Buy Now',
  proceedToCheckout: 'Proceed To Checkout',
  noItems: 'No Items in Cart',
};
