export default {
  username: 'नमस्ते, राहुल',
  details: 'विवरण',
  home: 'होम',
  more: 'और',
  favourite: 'पसंदीदा',
  category: 'श्रेणी',
  cart: 'कार्ट',
  change_language: 'भाषा बदलें',
  search: 'उत्पाद या स्टोर खोजें',
  delivery: 'पहुंचान',
  address: 'ग्रीन वे 3000, सिल्हेट',
  within: 'के भीतर',
  hour: '1 घंटा',
  recommended: 'सिफारिश किया गया है',
  discount: '50% छूट',
  get: 'प्राप्त करें',
  order: 'पहले 03 ऑर्डर पर',
  off: 'बंद',
  shopping: 'शॉपिंग कार्ट',
  subTotal: 'कुल मिलाकर',
  deliveryPrice: 'डिलीवरी',
  total: 'कुल',
  addToCart: 'कार्ट में डालें',
  buyNow: 'अब खरीदें',
  proceedToCheckout: 'चेकआउट करें',
};
